import { Bookmark, Camera, Heart, Image, MessageCircle, MoreHorizontal, Search, Send, Sparkles, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { NavLink } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";
import { subscribeToVavagramPosts } from "../services/vavagramService";

const tabs = ["Feed", "Salvos", "Perfil"];

export default function VavagramPage() {
  const { profile } = useAuth();
  const [posts, setPosts] = useState([]);
  const [tab, setTab] = useState("Feed");
  const [error, setError] = useState("");
  useEffect(() => subscribeToVavagramPosts(setPosts, (snapshotError) => setError(snapshotError.message)), []);
  return <div className="vavagram-page"><header className="vavagram-topbar"><NavLink className="vavagram-brand" to="/vavagram"><span><Camera size={19} /></span><strong>VAVAGRAM</strong></NavLink><label className="vavagram-search"><Search size={15} /><input placeholder="Pesquisar no Vavagram" aria-label="Pesquisar no Vavagram" /></label><div className="vavagram-tools"><button className="vavagram-icon" title="Mensagens"><Send size={17} /></button><button className="vavagram-icon" title="Notificações"><Heart size={17} /></button><div className="avatar avatar-fallback">{profile?.displayName?.[0] ?? "V"}</div></div></header><div className="vavagram-layout"><aside className="vavagram-sidebar"><div className="vavagram-profile-card"><div className="avatar avatar-fallback vavagram-avatar">{profile?.displayName?.[0] ?? "V"}</div><strong>{profile?.displayName ?? "Usuário"}</strong><span>@{profile?.username ?? "username"}</span><p>{profile?.bio || "Seu perfil visual no Vavagang."}</p><NavLink className="vavagram-profile-link" to="/settings">Editar perfil</NavLink></div><nav className="vavagram-tabs" aria-label="Vavagram"><button className={tab === "Feed" ? "active" : ""} onClick={() => setTab("Feed")}><Sparkles size={16} /> Feed</button><button className={tab === "Salvos" ? "active" : ""} onClick={() => setTab("Salvos")}><Bookmark size={16} /> Salvos</button><button className={tab === "Perfil" ? "active" : ""} onClick={() => setTab("Perfil")}><UserRound size={16} /> Meu perfil</button></nav><div className="vavagram-sidebar-note"><span>VAVAGRAM</span><p>Uma rede visual feita para a sua comunidade.</p></div></aside><main className="vavagram-feed"><div className="vavagram-feed-heading"><div><p className="eyebrow">Rede visual</p><h1>{tab}</h1></div><button className="vavagram-create" disabled title="Publicações serão habilitadas na próxima etapa"><Image size={16} /> Criar</button></div>{tab === "Perfil" ? <ProfileOverview profile={profile} posts={posts} /> : tab === "Salvos" ? <EmptyVavagram icon={Bookmark} title="Nenhuma publicação salva" text="Publicações salvas por você aparecerão nesta área." /> : error ? <p className="settings-error">{error}</p> : posts.length === 0 ? <EmptyVavagram icon={Camera} title="Seu feed está esperando" text="Quando houver publicações reais no Vavagram, elas aparecerão aqui." /> : <div className="vavagram-post-list">{posts.map((post) => <VavagramPost key={post.id} post={post} />)}</div>}</main><aside className="vavagram-rightbar"><div className="stories-heading"><strong>Stories</strong><span>24 horas</span></div><div className="stories-empty"><div className="story-add"><PlusIcon /></div><p>Nenhum story ativo</p><span>Stories reais aparecerão aqui.</span></div><div className="vavagram-right-section"><div><strong>Seu espaço</strong><span>privado</span></div><p>Perfil, posts e mídia ficam vinculados à sua conta autenticada.</p></div></aside></div></div>;
}

function VavagramPost({ post }) { return <article className="vavagram-post"><header><div className="avatar avatar-fallback">{post.displayName?.[0] ?? "V"}</div><div><strong>{post.displayName ?? "Usuário"}</strong><span>@{post.username ?? "username"} · {formatPostDate(post.createdAt)}</span></div><button className="vavagram-more" title="Mais opções"><MoreHorizontal size={17} /></button></header>{post.caption && <p className="post-caption">{post.caption}</p>}{post.mediaUrl ? <img className="post-media" src={post.mediaUrl} alt={post.caption ?? "Publicação do Vavagram"} /> : <div className="post-text-only"><Sparkles size={20} /><p>{post.text ?? "Publicação visual"}</p></div>}<footer><div><button title="Curtir"><Heart size={17} /> {post.likeCount ?? 0}</button><button title="Comentar"><MessageCircle size={17} /> {post.commentCount ?? 0}</button><button title="Compartilhar"><Send size={17} /></button></div><button title="Salvar"><Bookmark size={17} /></button></footer></article>; }
function ProfileOverview({ profile, posts }) { return <div className="profile-overview"><div className="profile-cover" /> <div className="profile-overview-content"><div className="avatar avatar-fallback profile-overview-avatar">{profile?.displayName?.[0] ?? "V"}</div><h2>{profile?.displayName ?? "Usuário"}</h2><span>@{profile?.username ?? "username"}</span><p>{profile?.bio || "Adicione uma bio ao seu perfil."}</p><div className="profile-stats"><span><b>{posts.filter((post) => post.authorId === profile?.uid).length}</b> posts</span><span><b>--</b> seguidores</span><span><b>--</b> seguindo</span></div></div></div>; }
function EmptyVavagram({ icon: Icon, title, text }) { return <div className="vavagram-empty"><div><Icon size={23} /></div><h2>{title}</h2><p>{text}</p></div>; }
function PlusIcon() { return <span className="story-plus">+</span>; }
function formatPostDate(value) { if (!value) return "agora"; const date = value.toDate ? value.toDate() : new Date(value); return Number.isNaN(date.getTime()) ? "agora" : new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(date); }